version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/antsa-live/haystack-service

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
  AfterInstall:
    - location: scripts/pip_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60