name: Deploy Haystack to Azure AU

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Create deployment package'
      run: |
        mkdir deploy
        cp *.py deploy/ || true
        cp requirements.txt deploy/
        cp -r venv/lib/python3.*/site-packages/* deploy/ || true
        
        # Create startup script
        cat > deploy/startup.sh << 'EOF'
#!/bin/bash
cd /home/site/wwwroot
python -m uvicorn main:app --host 0.0.0.0 --port 8000
EOF
        chmod +x deploy/startup.sh

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'antsa-haystack-au-production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_HAYSTACK_PUBLISHPROFILE_AU_PRODUCTION }}
        package: './deploy'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_AU }}
        REDIS_URL: ${{ secrets.REDIS_URL_AU }}
        DATABASE_URL: ${{ secrets.DATABASE_URL_AU }}
        NESTJS_API_URL: 'https://au.api.antsa.ai'
        LOG_LEVEL: 'INFO'
        HOST: '0.0.0.0'
        PORT: '8000'
        SHOW_TOOL_BANNER: 'true'
        SHOW_RAW_TOOL_JSON: 'false'
        MAX_REQUESTS_PER_USER: '10'
        SESSION_TIMEOUT_MINUTES: '240'
        MAX_CONCURRENT_REQUESTS: '10000'
        COUNTRY_CODE: 'au'
